name: Bot Actions

on:

  schedule:
    - cron: "11 4 * * 5,1,4"

  workflow_dispatch:

jobs:

  bot:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize GitHub CLI
        run: |
          echo ${{ secrets.BOT_TOKEN }} > token.txt
          gh auth login --with-token < token.txt
          # gh auth status
          rm -f token.txt

      - name: Install and initialize AI Code CLI
        run: | 
          curl -fsSL https://opencode.ai/install | bash
          # npm install -g @kilocode/cli
          # npm i -g @github/copilot
          # npm i -g opencode-ai

      - name: Enable Spec tools for supported repositories
        run: |
          # npm i -g @fission-ai/openspec@latest
          # uv tool install specify-cli --from git+https://github.com/github/spec-kit.git

      - name: AI work
        run: |
          echo ${GITHUB_RUN_ID} > runner.txt
          echo ${{ secrets.LARK_WEBHOOK_SECRET }} > lark.txt
          # kilo run --auto "Wake up and start working. See @AGENTS.md for more information." -m kilo-auto/free
          opencode run "Wake up and start working. See @AGENTS.md for more information." -m opencode/big-pickle
          # copilot -p "Wake up and start working. See @AGENTS.md for more information." --yolo --model gpt-4.1
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
          COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_TOKEN }}
