name: Bot Actions

on:

  schedule:
    - cron: "11 4 * * 5,1,4"

  workflow_dispatch:

jobs:

  bot:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize GitHub CLI
        run: |
          echo ${{ secrets.BOT_TOKEN }} > token.txt
          gh auth login --with-token < token.txt
          # gh auth status
          rm -f token.txt

      - name: Install and initialize AI Code CLI
        run: | 
          curl -fsSL https://opencode.ai/install | bash # Recommended.
          # npm i -g @github/copilot # For users who prefers Copilot-powered runs
          # npm i -g opencode-ai # For Windows runners

      - name: Enable Spec tools for supported repositories
        run: |
          npm i -g @fission-ai/openspec@latest
          ## Spec Kit is temporarily unavailable (and I don't know why).
          # uv tool install specify-cli --from git+https://github.com/github/spec-kit.git

      - name: AI work
        run: |
          echo ${GITHUB_RUN_ID} > runner.txt
          echo ${{ secrets.LARK_WEBHOOK_SECRET }} > lark.txt # used to send Lark messages
          opencode run "Wake up and start working. See @AGENTS.md for more information." # Edit opencode.json to change model. Big Pickle is good enough (it's said that it's actually GLM-4.6/4.7)
          # copilot -p "Wake up and start working. See @AGENTS.md for more information." --yolo --model gpt-4.1 # For users who prefers Copilot-powered runs
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
          # COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_TOKEN }} # For users who prefers Copilot-powered runs
